name = "server"
compatibility_date = "2024-05-24"
node_compat = true

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZGJkZjk4YmMtNDI2OC00NGNjLWJiNTktNDcwNGRiNDEzZWMwIiwidGVuYW50X2lkIjoiMWYwNmMwODJkZjM5ZmYzOTZkNGQ4ZTAyNTg4M2EwYzMyYzc4YTFkNzliNWEwY2JjY2EwYmJmNGVkZGMwY2Q1MSIsImludGVybmFsX3NlY3JldCI6IjBjMDQ3MGEwLThiZmEtNGViYS1iN2YzLTNkOWM3YjBlYjgxMiJ9.WeEkMfUUiOah5LkLGTQeDyR3GeauFH2ovLYyM0UIF1M"

FRONTEND_URL="http://localhost:5173"

JWT_ACCESS_TOKEN_SECRET="VnKFbWRE0CEBCgCDd7efGtrCADEEB4487519AEBE5C8ECFB4C698RWPFUajiDID81ZZceWI7Cb5fHMYdJcEq3DspmwIEtRyPBxz6th6WWntt3TsN3J2cPo0eOUbqz"

JWT_REFRESH_TOKEN_SECRET="18A7825B411D55AC58BED0VuSmmVmiRNx41pYE3D5D77A3B26E583Xi2PpizmSLLeKHC5GqUdJm4aZpDU8S5KHF8gA7E8A6519C735cvR2DxaHGyN5ij2QX%DTvKe@es&ep5xp>%NI6QAD033A33547"

R2_URL="https://pub-291575832fc04fdeac7b59be031f8c6f.r2.dev"

GEMINI_KEY="AIzaSyDdJiyhHHGMOeKqiiGnc3WMXiq64Cqcrbk"

REDIS_URL="rediss://default:Ad3kAAIncDE2MjI2NGY3YTliOWE0MjRiOTAyZmYyOWMyNmQxMGQyZXAxNTY4MDQ@saving-kid-56804.upstash.io:6379"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

 [[r2_buckets]]
 binding = "BLOG_APP_UPLOADS"
 bucket_name = "blog-app-uploads"


# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
